### ISSUE TITLE
[FR] Daily / Hourly forecast

### ISSUE THREAD

**Issue by Ulrar** [bramkragten/weather-card#158] opened 2023-09-07 08:53 UTC
Hi,

Now that HA has deprecated the forecast attribute, and instead uses a service call with an option of daily / hourly, could this card be updated to expose that ?

The card already has an hourly option that seems reserved for openweathermap (or at least it changes nothing for me), maybe that could be updated / extended to use the new service instead ?
I could easily imagine having two instances of this card on my dashboard under a swipe card, one for daily and one for hourly.

Thanks !

**Comment by bramkragten** [comment] 2023-09-11 20:47
Yes, I will add this :-)

**Comment by Scoop2389** [comment] 2023-10-24 15:31
Hello, it seems like my issue #159 may be a duplicate of this one. Is this still being worked on?

**Comment by Henry-Sir** [comment] 2023-11-09 08:45
Any updates?

**Comment by mdezzi** [comment] 2023-11-29 23:00
@bramkragten is this card being maintained or should i look for another solution. without updating to the new forecast structure, this card is all but worthless in its current state.

**Comment by bramkragten** [comment] 2023-12-09 23:15
Basic support for the new forecast format was added in https://github.com/bramkragten/weather-card/commit/b665f6cab338073ae3ced3948e21001553794430

**Closed** 2023-12-09 23:16 UTC
