### ISSUE TITLE
[BUG] Precipitation shows too many decimals/breaks layout

### ISSUE THREAD

**Issue by david-kalbermatten** [bramkragten/weather-card#65] opened 2020-08-13 14:55 UTC
### What is wrong?
The daily precipitation has no rounding function which causes the layout of the weather card to break (Screenshot below)

### What should be changed?
Please add `Math.round(precipitation*10)\10` in line 296 like below to have the output be rounded to 1 decimal point.
```js
[...]
${!this._config.hide_precipitation &&
daily.precipitation !== undefined &&
daily.precipitation !== null
  ? html`
    <div class="precipitation">
    ${Math.round(daily.precipitation * 10) \ 10} ${this.getUnit("precipitation")}
    </div>
    `
  : ""}
[...]
```

### Screenshots
![image](https://user-images.githubusercontent.com/45201085/90149190-81b89280-dd84-11ea-8e66-70902d81c42e.png)

**Comment by david-kalbermatten** [comment] 2020-08-14 11:24
I made the fix myself #66. If anyone is interested in using it now, you can do so by adding my [fork](https://github.com/david-kalbermatten/weather-card) to HACS.

![image](https://user-images.githubusercontent.com/45201085/90244522-37d9b600-de31-11ea-8ccf-416e1e14f13f.png)

**Comment by silviudc** [comment] 2020-08-15 19:11
Hmm I tried that but still the same, I just over-wrote the weather-card.js file that was there. Anything else?

**Comment by silviudc** [comment] 2020-08-17 07:07
I used your fork but it works only sometimes it seems:
![image](https://user-images.githubusercontent.com/17740184/90367362-ad779900-e060-11ea-8bdc-3076ee8c4d44.png)

**Comment by berrywhite96** [comment] 2020-08-17 09:33
> I used your fork but it works only sometimes it seems:
> ![image](https://user-images.githubusercontent.com/17740184/90367362-ad779900-e060-11ea-8bdc-3076ee8c4d44.png)

Maybe you still have the `weather-card.js.gz` and `weather-card-editor.js.gz` files in your dir? Try removing them, they are just compressed versions of the original file.

**Comment by silviudc** [comment] 2020-08-17 12:07
Tried that deleting the gz files and added new files from the fork and still the same
![image](https://user-images.githubusercontent.com/17740184/90394445-964da100-e08a-11ea-8b69-f51e777f019c.png)

**Comment by bramkragten** [comment] 2020-08-17 12:58
What integration are you using?

**Comment by silviudc** [comment] 2020-08-17 14:50
`current: true
details: true
entity: weather.home
forecast: true
type: 'custom:weather-card'`

**Comment by bramkragten** [comment] 2020-08-17 16:29
I mean what integration in Home Assistant (weather.home) is providing this data?

**Comment by silviudc** [comment] 2020-08-17 18:42
The built in HA weather entity I guess:
```
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
```

**Comment by DENightOne** [comment] 2020-08-17 20:29
I have the same problem as above and logged an issue on the HA forum.  The problem is with the HA built in met.no api call , the changed it a few days ago and now it returns xml and precipitation has lots of decimal places. (I cant recall if there previous api returned precipitation at all)..   They say that they will fix the issue as it not only messes up the formatting of your card but the default card as well.

As a quick work around just did the following to your code
line 296:  ${(daily.precipitation).toFixed(1)}

**Comment by DENightOne** [comment] 2020-08-17 20:34
> 
> 
> Tried deleting the gz files and added new files from the fork and still the same
> ![image](https://user-images.githubusercontent.com/17740184/90394445-964da100-e08a-11ea-8b69-f51e777f019c.png)
> 
> ![image](https://user-images.githubusercontent.com/17740184/90394864-5f2bbf80-e08b-11ea-8012-36bee1982100.png)
> 
> Am I missing something?

Not sure if this helps, but restarting HA is not enough, you need to hold down shift and press the refresh button on your browser, as it is caching the old javascript (or clear your browser cache)....ps....shift and refresh is a lot quicker

**Comment by silviudc** [comment] 2020-08-18 09:46
Tried that on line 296 and it fixed some but not all

![image](https://user-images.githubusercontent.com/17740184/90498256-f81c1280-e13f-11ea-9bb1-96ac648b8367.png)

Rebooted HA a few times, CTRL+F5 the browser and the same.
Guess need to wait for the full fix

**Comment by bramkragten** [comment] 2020-08-18 11:28
Fixed in master

**Closed by bramkragten** 2020-08-18 11:28 UTC
