### ISSUE TITLE
No visibility data with buienradar weather

### ISSUE THREAD

**Issue by dystechnic** [bramkragten/weather-card#48] opened 2020-05-01 11:43 UTC
Hi,

I've got buienradar as source for the weather-card and everything is fine except for the visibility info.
I am using the buienradar platform withing HASS and not the sensors version.
![weerkaart](https://user-images.githubusercontent.com/36402924/80803056-719fed00-8bb1-11ea-9ade-6314f92887e8.png)

I tried using the sensors integration of buienradar but that didn't work.

Regards.

**Comment by jjmonteiro** [comment] 2020-05-13 13:49
duplicate of #37

**Closed** 2020-05-13 16:34 UTC
