### ISSUE TITLE
Card dissapears

### ISSUE THREAD

**Issue by misza-do** [bramkragten/weather-card#81] opened 2020-10-14 17:45 UTC
Weather card disappears from frontend from time to time. This happens both in browser and mobile app. Clicking on "Edit Dashbord" make cars visible again.

**Comment by wisesokol** [comment] 2020-10-15 18:06
i have this problem too

**Comment by pgdg71** [comment] 2020-10-17 05:55
Mee too. If you edit Lovelace the card is suddently shown

**Comment by fofinho11** [comment] 2020-10-20 06:36
Same.
In the app on iOS it seems to be fine but on Android it disappears.

**Comment by leva3000** [comment] 2020-10-21 08:55
It's a general Home Assistant issue with custom cards. The issue is probably related to the lazy loading changes made in HA 0.116. For me, it's working just to unhide and hide again the sidebar.

**Comment by dmutpuul** [comment] 2020-10-21 14:23
> It's a general Home Assistant issue with custom cards. The issue is probably related to the lazy loading changes made in HA 0.116. For me, it's working just to unhide and hide again the sidebar.

Thank you, your hack takes less time))

**Comment by bramkragten** [comment] 2020-10-21 16:52
This is fixed in the HA beta that will be release today

**Closed by bramkragten** 2020-10-21 16:52 UTC
